import type { Metadata } from "next";
import { CopyTextButton } from "@/components/copy-text-button";
import { DonationConfirmationForm } from "@/components/donation-confirmation-form";

export const metadata: Metadata = { title: "Support JWS | Janaza Welfare Society", description: "Support Janaza Welfare Society by bank transfer and securely submit your transfer confirmation." };

export default function SupportPage() {
  return <main className="bg-gradient-to-b from-light-background to-white px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-5xl"><header className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">Community Support</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Support JWS</h1><div className="section-ornament" aria-hidden="true"><span /></div><p className="mt-5 leading-7 text-muted">Your contribution helps Janaza Welfare Society continue supporting families and the community with dignity, care, and compassion. Donations are made by manual bank transfer.</p></header>
    <section aria-labelledby="bank-details" className="mx-auto mt-12 max-w-3xl overflow-hidden rounded-3xl border border-primary/40 bg-white shadow-[0_20px_60px_rgba(16,42,42,0.08)]"><div className="bg-foreground px-6 py-4 text-white"><h2 id="bank-details" className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Bank Transfer Details</h2></div><dl className="grid gap-px bg-border sm:grid-cols-2"><BankDetail label="Bank" value="Bank of Ceylon" /><BankDetail label="Branch" value="Kattankudy Branch" /><BankDetail label="Account Name" value="Janaza Welfare Society" /><div className="bg-white p-6"><dt className="text-xs font-semibold uppercase tracking-wider text-muted">Account Number</dt><dd className="mt-2 text-2xl font-semibold tracking-wider">0083413668</dd><div className="mt-4"><CopyTextButton value="0083413668" label="Copy Account Number" /></div></div></dl></section>
    <section id="confirmation" aria-labelledby="confirmation-title" className="scroll-mt-8 pt-16"><div className="mb-7"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Transfer Confirmation</p><h2 id="confirmation-title" className="mt-2 text-3xl font-semibold">Already transferred your donation?</h2><p className="mt-3 max-w-2xl leading-7 text-muted">Submit the details below so JWS can verify your contribution. This form records a bank-transfer confirmation only; it does not process a payment.</p></div><DonationConfirmationForm /></section>
    <aside className="mt-8 rounded-2xl border border-border bg-white p-6 text-sm leading-6 text-muted"><p className="font-semibold text-foreground">Privacy and verification</p><p className="mt-2">Your contact details and receipt are kept private and are available only to authorized JWS administrators for verification. Submitting this form does not mean the transfer has been verified.</p></aside>
  </div></main>;
}

function BankDetail({ label, value }: { label: string; value: string }) { return <div className="bg-white p-6"><dt className="text-xs font-semibold uppercase tracking-wider text-muted">{label}</dt><dd className="mt-2 text-lg font-semibold">{value}</dd></div>; }
