"use client";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
type Banner={id:string;title:string;imageUrl:string;description:string|null};
export function AdvertisementCarousel({banners}:{banners:Banner[]}){const[index,setIndex]=useState(0);const[paused,setPaused]=useState(false);const multiple=banners.length>1;const move=useCallback((by:number)=>setIndex(current=>(current+by+banners.length)%banners.length),[banners.length]);
  useEffect(()=>{if(!multiple||paused||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>move(1),10_000);return()=>window.clearInterval(timer);},[multiple,paused,move]);
  const banner=banners[index];
  return <div className="mx-auto w-full max-w-7xl overflow-hidden" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={()=>setPaused(false)}><article className="overflow-hidden rounded-2xl border border-border bg-light-background shadow-[0_8px_28px_rgba(16,42,42,.05)]"><p className="px-4 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-muted">Advertisement</p><Image unoptimized src={`/advertisement-images/${banner.imageUrl}`} alt={banner.title} width={1600} height={520} priority={index===0} className="h-44 w-full object-cover sm:h-52 md:h-[280px] lg:h-[300px]"/><div className="flex flex-wrap items-center justify-between gap-2 px-3 py-3 sm:px-4">{banner.description&&<p className="min-w-0 flex-1 truncate text-xs text-muted sm:text-sm">{banner.description}</p>}<div className="ml-auto flex shrink-0 items-center gap-2"><Link href={`/advertisements/${banner.id}`} className="inline-flex min-h-10 items-center justify-center rounded-full bg-primary px-4 text-xs font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-foreground sm:text-sm">View Advertisement</Link>{multiple&&<div className="flex items-center gap-1"><button type="button" onClick={()=>move(-1)} aria-label="Previous advertisement" className="flex size-10 items-center justify-center rounded-full border border-border bg-white text-xl font-semibold focus-visible:outline-2 focus-visible:outline-primary">‹</button><button type="button" onClick={()=>move(1)} aria-label="Next advertisement" className="flex size-10 items-center justify-center rounded-full border border-border bg-white text-xl font-semibold focus-visible:outline-2 focus-visible:outline-primary">›</button></div>}</div></div></article>{multiple&&<div className="mt-2 flex justify-center gap-2" role="group" aria-label="Select advertisement">{banners.map((item,i)=><button key={item.id} type="button" onClick={()=>setIndex(i)} aria-label={`Show advertisement ${i+1}: ${item.title}`} aria-current={i===index?"true":undefined} className={`size-3 rounded-full border border-foreground/30 ${i===index?"bg-primary":"bg-white"}`}/>)}</div>}</div>;
}
