"use client";
import Image from "next/image";
import Link from "next/link";
import { useActionState, useEffect, useState } from "react";
import type { AdState } from "@/app/admin/(protected)/advertisements/actions";
const input = "mt-2 min-h-12 w-full rounded-xl border border-border bg-white px-4 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20";
type Initial = { title:string; description:string; startsAt:string; endsAt:string; displayOrder:number; isActive:boolean; hasImage:boolean; imageUrl?:string };
export function AdvertisementForm({ action, initial }: { action:(state:AdState,data:FormData)=>Promise<AdState>; initial:Initial }) {
  const [state, formAction, pending] = useActionState(action, {}); const [preview, setPreview] = useState<string | null>(null); const [filename, setFilename] = useState("");
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  return <form action={formAction} className="mt-7 space-y-6 rounded-2xl border border-border bg-white p-5 shadow-[0_8px_28px_rgba(16,42,42,.05)] sm:p-7">
    <div><label htmlFor="title" className="text-sm font-semibold">Banner Title</label><input id="title" name="title" required maxLength={191} defaultValue={initial.title} className={input}/></div>
    <fieldset className="rounded-2xl border-2 border-dashed border-primary/60 bg-light-background p-4 sm:p-5"><legend className="px-2 text-sm font-semibold">Choose Banner Image</legend><label htmlFor="image" className="mt-2 flex min-h-14 cursor-pointer items-center justify-center rounded-xl bg-primary px-5 py-3 text-center text-sm font-semibold focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-foreground"><span>{filename || (initial.hasImage ? "Choose Replacement Image" : "Choose JPEG, PNG, or WEBP")}</span><input id="image" name="image" type="file" required={!initial.hasImage} accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => { const file=event.target.files?.[0]; if(preview)URL.revokeObjectURL(preview); setFilename(file?.name ?? ""); setPreview(file ? URL.createObjectURL(file) : null); }}/></label><p className="mt-2 text-center text-xs text-muted">Maximum 5 MB. The selected file is never restored after a validation error.</p>{(preview || initial.imageUrl) && <div className="mt-4 overflow-hidden rounded-xl border border-border bg-white"><Image unoptimized src={preview ?? initial.imageUrl!} alt="Selected banner preview" width={1200} height={400} className="aspect-[3/1] min-h-32 w-full object-cover"/></div>}</fieldset>
    <div><label htmlFor="description" className="text-sm font-semibold">Optional Description</label><textarea id="description" name="description" maxLength={500} rows={3} defaultValue={initial.description} className={input}/></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="startsAt" className="text-sm font-semibold">Start Date/Time <span className="font-normal text-muted">(optional)</span></label><input id="startsAt" name="startsAt" type="datetime-local" defaultValue={initial.startsAt} className={input}/></div><div><label htmlFor="endsAt" className="text-sm font-semibold">End Date/Time <span className="font-normal text-muted">(optional)</span></label><input id="endsAt" name="endsAt" type="datetime-local" defaultValue={initial.endsAt} className={input}/></div></div>
    <div><label htmlFor="displayOrder" className="text-sm font-semibold">Display Order</label><input id="displayOrder" name="displayOrder" type="number" step="1" required defaultValue={initial.displayOrder} className={input}/></div>
    <label className="flex min-h-14 items-center gap-3 rounded-xl border border-border p-4 text-sm font-semibold"><input name="isActive" type="checkbox" defaultChecked={initial.isActive} className="size-5 accent-[#45E8CD]"/><span><span className="block">Active / Published</span><span className="mt-1 block text-xs font-normal text-muted">The banner is public only while it is active and within its schedule.</span></span></label>
    <div aria-live="polite">{state.error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{state.error}</p>}{state.success && <p role="status" className="rounded-xl border border-primary/40 bg-primary/10 p-4 text-sm font-semibold">✓ {state.success}</p>}</div>
    <div className="flex flex-col-reverse gap-3 sm:flex-row"><Link href="/admin/advertisements" className="inline-flex min-h-12 items-center justify-center rounded-full border border-border px-6 text-sm font-semibold">Cancel / Back</Link><button disabled={pending} className="min-h-12 rounded-full bg-primary px-7 font-semibold disabled:opacity-60">{pending ? "Saving..." : initial.isActive ? "Save / Publish" : "Save Advertisement"}</button></div>
  </form>;
}
