import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdminOrSupervisor } from "@/lib/permissions";
import { TaskStatusBadge } from "@/components/employee/task-status-badge";
export default async function SupervisorTasksPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  await requireAdminOrSupervisor(); const filter = (await searchParams).status;
  const statuses = filter === "in-progress" ? ["IN_PROGRESS"] as const : filter === "completed" ? ["COMPLETED"] as const : ["ASSIGNED", "ACKNOWLEDGED"] as const;
  const tasks = await prisma.taskAssignment.findMany({ where: { ...(filter === "completed" ? {} : { isActive: true }), status: { in: [...statuses] } }, orderBy: { assignedAt: "desc" }, include: { employee: { select: { fullName: true } }, request: { select: { id: true, requestCode: true, serviceType: true, area: true } } } });
  return <div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-primary">Operations</p><h1 className="mt-1 text-3xl font-semibold">Tasks</h1><div className="mt-5 flex flex-wrap gap-2">{[["assigned","Assigned"],["in-progress","In Progress"],["completed","Completed"]].map(([v,l]) => <Link key={v} href={`/supervisor/tasks?status=${v}`} className="min-h-11 rounded-full border border-border px-4 py-3 text-sm font-semibold">{l}</Link>)}</div><div className="mt-6 space-y-4">{tasks.map((t) => <article key={t.id} className="grid gap-4 rounded-2xl border border-border bg-white p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><p className="text-xs font-semibold text-primary">{t.request.requestCode}</p><p className="mt-1 font-semibold">{t.request.serviceType}</p><p className="text-sm text-muted">{t.request.area}</p></div><div><p className="text-sm font-semibold">{t.employee.fullName}</p><div className="mt-2"><TaskStatusBadge status={t.status}/></div></div><Link href={`/supervisor/requests/${t.request.id}`} className="min-h-11 rounded-xl border border-border px-4 py-3 text-center text-sm font-semibold">View / Reassign</Link></article>)}</div>{!tasks.length && <p className="mt-6 rounded-2xl border border-border bg-white p-10 text-center text-muted">No tasks in this group.</p>}</div>;
}
